{{- if .Values.limitTraficToNamespace }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "openvpn-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "openvpn-server.name" . }}
    helm.sh/chart: {{ include "openvpn-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector: { }
  policyTypes:
    - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - {{ .Values.limitedCidr }}
{{- end }}
