kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "openvpn-server.name" . }}
  labels: {{- include "openvpn-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "openvpn-server.storageClass" . }}
