{{- if (include "openvpn-server.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openvpn-server.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"
    {{- with .Values.easyrsa.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  openvpn-server-passphrase: {{ include "openvpn-server.passphrase" . | b64enc | quote }}
{{- end -}}
