apiVersion: v1
kind: Service
metadata:
  name: "{{ include "openvpn-server.fullname" . }}-{{ .Values.service.protocol | lower }}"
  labels:
    {{- include "openvpn-server.labels" . | nindent 4 }}
    role: {{ .Values.service.protocol | lower }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "openvpn-{{ .Values.service.protocol | lower }}"
      protocol: {{ .Values.service.protocol }}
      name: "openvpn-{{ .Values.service.protocol | lower }}"
  selector:
    {{- include "openvpn-server.selectorLabels" . | nindent 4 }}
    role: {{ .Values.service.protocol | lower }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
---
{{- if .Values.service.fallback }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "openvpn-server.fullname" . }}-{{ include "openvpn-server.fallbackProtocol" . }}"
  labels:
    {{- include "openvpn-server.labels" . | nindent 4 }}
    role: {{ include "openvpn-server.fallbackProtocol" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: "openvpn-{{ include "openvpn-server.fallbackProtocol" . }}"
      protocol: {{ include "openvpn-server.fallbackProtocol" . | upper }}
      name: "openvpn-{{ include "openvpn-server.fallbackProtocol" . }}"
  selector:
    {{- include "openvpn-server.selectorLabels" . | nindent 4 }}
    role: {{ include "openvpn-server.fallbackProtocol" . }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
