apiVersion: v1
kind: Service
metadata:
  name: {{ include "commander.fullname" . }}
  labels:
    {{- include "commander.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "commander.selectorLabels" . | nindent 4 }}
