{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "duckdns.token-secret" . }}
  labels:
    app: {{ template "duckdns.name" . }}
    chart: {{ template "duckdns.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.token }}
  token: {{ .Values.token | b64enc | quote }}
  {{- else }}
  token: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}
