---
extraPorts:
  - name: peerflix
    containerPort: 9000
    protocol: TCP

extraVolumes:
  volumes:
    - name: peerflix-data
      emptyDir: {}

sidecars:
  - name: peerflix
    image: shokohsc/peerflix-server:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    readinessProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    startupProbe:
      exec:
        command:
          - curl
          - -lsX
          - GET
          - "http://localhost:9000"
    volumeMounts:
      - name: peerflix-data
        mountPath: /tmp/torrent-stream
