apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.smb.port }}
      targetPort: smb
      protocol: TCP
      name: smb
    - port: {{ .Values.service.netbios.port }}
      targetPort: netbios
      protocol: TCP
      name: netbios
  selector:
    {{- include "samba.selectorLabels" . | nindent 4 }}
