---
extraVolumes:
  volumes:
    - name: pihole
      emptyDir: {}
    - name: dnsmasq
      emptyDir: {}
  volumeMounts:
    - name: pihole
      mountPath: /etc/pihole
    - name: dnsmasq
      mountPath: /etc/dnsmasq.d
