apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvpn-client.fullname" . }}-sidekick
  labels:
    {{- include "openvpn-client.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openvpn-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.sidekick.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openvpn-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.sidekick.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-sidekick
          securityContext:
            {{- toYaml .Values.sidekick.securityContext | nindent 12 }}
          image: "{{ .Values.sidekick.image.repository }}:{{ .Values.sidekick.image.tag }}"
          imagePullPolicy: {{ .Values.sidekick.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
            {{- range $key, $value := .Values.sidekick.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api
              port: http
          livenessProbe:
            httpGet:
              path: /api
              port: http
          readinessProbe:
            httpGet:
              path: /api
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openvpn-client.fullname" . }}
  labels:
    {{- include "openvpn-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openvpn-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openvpn-client.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      initContainers:
        - name: curl-sidekick
          image: curlimages/curl
          imagePullPolicy: IfNotPresent
          args:
            - -GLs
            - "http://{{ include "openvpn-client.fullname" . }}-sidekick:{{ .Values.sidekick.service.port }}/api/"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - /usr/bin/sidekick.sh
          env:
            - name: SIDEKICK_URL
              value: "http://{{ include "openvpn-client.fullname" . }}-sidekick:{{ .Values.sidekick.service.port }}/api/ovpn"
            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $index, $port := .Values.extraPorts }}
            - name: {{ printf "%s_%d" "VPNPORT" (add (index $index) 1) }}
              value: {{ $port | quote }}
            {{- end }}
          {{- if .Values.extraPorts }}
          ports:
            {{- range $port := .Values.extraPorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - ps -fe | grep "open[v]pn --cd /vpn --config /vpn/vpn_conf.ovpn"
            periodSeconds: 2
            failureThreshold: 1
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - ps -fe | grep "open[v]pn --cd /vpn --config /vpn/vpn_conf.ovpn"
            periodSeconds: 2
            failureThreshold: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: sidekick-script
              mountPath: /usr/bin/sidekick.sh
              subPath: sidekick.sh
            - name: openvpn-script
              mountPath: /usr/bin/openvpn.sh
              subPath: openvpn.sh
          {{- if and .Values.extraVolumes .Values.extraVolumes.volumeMounts }}
            {{- toYaml .Values.extraVolumes.volumeMounts | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: sidekick-script
          configMap:
            name: shell-scripts
            defaultMode: 0755
        - name: openvpn-script
          configMap:
            name: shell-scripts
            defaultMode: 0755
      {{- if and .Values.extraVolumes .Values.extraVolumes.volumes }}
        {{- toYaml .Values.extraVolumes.volumes | nindent 8 }}
      {{- end }}