name: Lint and Test Charts

on: pull_request

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        run: .github/helm-docs.sh

  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.16.9
  #         - v1.17.5
  #         - v1.18.8
  #         - v1.19.0
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh

  lint-test:
    runs-on: ubuntu-latest
    needs:
      # - kubeval-chart
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.16.9
          - v1.17.5
          - v1.18.8
          - v1.19.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.lint.outputs.changed == 'true'
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: ct.yaml
